version: '3'
services:
    aws-react-app:
        build: .
        container_name: docker-starter-kit-app
        image: docker-starter-kit-app
        command: npm start
        ports:
          - '3000:3000'
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
