version: '3'
services:
    front-end:
        build: .
        image: docker_react-app:lastest
        command: npm start
        volumes:
          - '.:/usr/src/app'
          - /usr/src/app/node_modules
