version: '3'
services:
  ui:
    build: .
    container_name: yourapp_ui
    image: yourapp_ui
    command: npm start
    ports:
    - '3000:3000'
    volumes:
    - .:/usr/src/app
     - /usr/src/app/node_modules
